homeassistant:
  name: Treetops
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

############################
#
# Include Files
#
############################

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
switch: !include switches.yaml
frontend: !include themes.yaml

############################
#
# Enablers
#
############################

config:
http:
  api_password: !secret http_password
updater:
discovery:
conversation:
history:
logbook:
#map:
sun:
tts:
  - platform: google
#cloud:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.152:3218

############################
#
# Components
#
############################

blink:
  username: !secret blink_username
  password: !secret blink_password
weather:
  - platform: metoffice
    api_key: !secret metoffice_key
notify:
  - name: NOTIFIER_PB
    platform: pushbullet
    api_key: !secret pushbullet
ifttt:
  key: !secret ifttt
ffmpeg:
  ffmpeg_bin: /usr/bin/avconv
zwave:
  usb_path: /dev/ttyACM0
device_tracker:
  - platform: nmap_tracker
    hosts: 
      - 192.168.1.124
      - 192.168.1.71
    home_interval: 20
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A11I6NWQ-if00-port0
  debug: True
  dummy: False

#######################
#
# Input Select
#
#######################

input_select:
  radio_downstairs:
    name: Station
    options:
      - BBC Radio 2
      - BBC Radio 6 Music
      - Absolute Radio 90s
      - BBC Radio 5 live
      - BBC Radio 5 live sports extra
    icon: mdi:radio
